//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AircraftRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AircraftRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirStar.Resources.AircraftRes", typeof(AircraftRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new aircraft.
        /// </summary>
        public static string AddNewAircraft {
            get {
                return ResourceManager.GetString("AddNewAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Brand&quot; shouldn&apos;t contain special characters.
        /// </summary>
        public static string BrandValidationCharacters {
            get {
                return ResourceManager.GetString("BrandValidationCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Brand&quot; field.
        /// </summary>
        public static string BrandValidationEmpty {
            get {
                return ResourceManager.GetString("BrandValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght should be between 2 to 50.
        /// </summary>
        public static string BrandValidationLenght {
            get {
                return ResourceManager.GetString("BrandValidationLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business class seats.
        /// </summary>
        public static string BusinessClassSeats {
            get {
                return ResourceManager.GetString("BusinessClassSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Business class seats&quot; field.
        /// </summary>
        public static string BusinessValidationEmpty {
            get {
                return ResourceManager.GetString("BusinessValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy class seats.
        /// </summary>
        public static string EconomyClassSeats {
            get {
                return ResourceManager.GetString("EconomyClassSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Economy class seats&quot; field.
        /// </summary>
        public static string EconomyValidationEmpty {
            get {
                return ResourceManager.GetString("EconomyValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to create such aircraft.
        /// </summary>
        public static string EconomyValidationGreater {
            get {
                return ResourceManager.GetString("EconomyValidationGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed. The aircraft operates flights.
        /// </summary>
        public static string ErrorMessege {
            get {
                return ResourceManager.GetString("ErrorMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First class seats.
        /// </summary>
        public static string FirstClassSeats {
            get {
                return ResourceManager.GetString("FirstClassSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;First class seats&quot; field.
        /// </summary>
        public static string FirstValidationEmpty {
            get {
                return ResourceManager.GetString("FirstValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum flight range.
        /// </summary>
        public static string MaxFlightRange {
            get {
                return ResourceManager.GetString("MaxFlightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Maximum flight range&quot; field.
        /// </summary>
        public static string MaxFlightRangeValidationEmpty {
            get {
                return ResourceManager.GetString("MaxFlightRangeValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to create such aircraft.
        /// </summary>
        public static string MaxFlightRangeValidationGreater {
            get {
                return ResourceManager.GetString("MaxFlightRangeValidationGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Model&quot; shouldn&apos;t contain special characters.
        /// </summary>
        public static string ModelValidationCharacters {
            get {
                return ResourceManager.GetString("ModelValidationCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Model&quot; field.
        /// </summary>
        public static string ModelValidationEmpty {
            get {
                return ResourceManager.GetString("ModelValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght should be between 2 to 50 symbols.
        /// </summary>
        public static string ModelValidationLenght {
            get {
                return ResourceManager.GetString("ModelValidationLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Picture&quot; field.
        /// </summary>
        public static string PictureFileValidationEmpty {
            get {
                return ResourceManager.GetString("PictureFileValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of build.
        /// </summary>
        public static string YearOfBuild {
            get {
                return ResourceManager.GetString("YearOfBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the &quot;Year of build&quot; field.
        /// </summary>
        public static string YearOfBuildValidationEmpty {
            get {
                return ResourceManager.GetString("YearOfBuildValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft is too old.
        /// </summary>
        public static string YearOfBuiltValidationGreater {
            get {
                return ResourceManager.GetString("YearOfBuiltValidationGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-existing date.
        /// </summary>
        public static string YearOfBuiltValidationLess {
            get {
                return ResourceManager.GetString("YearOfBuiltValidationLess", resourceCulture);
            }
        }
    }
}
